### ISSUE TITLE
Great project thanks! 

### ISSUE THREAD

**Issue by barnjamin** [headline-design/pipeline-ui#6]
Please check out my project here:

https://github.com/barnjamin/algorand-session-wallet
https://github.com/barnjamin/algorand-session-wallet-example

Goal is to support all the wallet options and abstract the API so wallet specific idiosyncrasies don't need to be handled by anyone that wants to build with web wallets.  I'd love for you to fork it or take it over completely? I'm terrible at front end stuff so it'd be great if there  was an attractive option for devs.

**Comment by headline-design** [comment]
Solid reference library!

**Comment by barnjamin** [comment]
Thanks! I'd be happy to nuke it if/when something like this gets implemented in Pipeline-UI tho ;)
