### ISSUE TITLE
AlgoFetch Component only user main-net 

### ISSUE THREAD

**Issue by AnthonyDasse** [headline-design/pipeline-ui#9]
unless I am mistaken, the component AlgoFetch only use main-net.

On the component ( https://github.com/headline-design/pipeline-ui/blob/main/src/AlgoFetch/index.js ) we can see hard coded : 

`let url2 =
      'https://algoexplorerapi.io/idx2/v2/accounts/' +
      props.address +
      '/transactions?limit=5'`

it's not possible to add this url management on the Pipeline class ( https://github.com/headline-design/pipeline-ui/blob/main/src/Pipeline/index.js ) and add 'main' props on the component or on an Pipeline variable ?

an other improve on this  the AlgoFetch component, add an limit props to manage the     '/transactions?limit=5'`

**Comment by headline-design** [comment]
You are correct - mainNet only right now. We will be adding this feature - thanks! Also, you can submit a pr for the doc page to specify that AlgoFetch is mainNet only right now.

**Comment by AnthonyDasse** [comment]
Ok ..
I will try to push on the documentation or directly a proposal on the code. Thank you for your Quick response.

**Comment by headline-design** [comment]
Closing this issue.
